# vim ft=yaml
#

notifications:
  email: false
language: python
python:
    - "2.7"
virtualenv:
  system_site_packages: true
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq -y python2.7-dev
    - sudo apt-get install -qq -y libblas-dev liblapack-dev gfortran 
install:
    - sudo pip install numpy
    - sudo pip install cython
    - sudo pip install pysam
    - travis_wait sudo pip install scipy
    - sudo pip install pandas
    - sudo pip install patsy
    - sudo pip install statsmodels
script:
    - sudo python2.7 setup.py install
    - "edd -h"

