# vim ft=yaml
#

language: python
python:
    - "2.7"
virtualenv:
  system_site_packages: true
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq -y python2.7-dev
    - sudo apt-get install -qq -y libblas-dev liblapack-dev gfortran 
install:

  - sudo pip install -q cython
  - sudo pip install -q pybedtools
  - sudo pip install -q numpy
  - sudo pip install -q pysam
  - travis_wait sudo pip install -q scipy
  - sudo pip install -q pandas
  - sudo pip install -q patsy
  - sudo pip install -q statsmodels
script:
    - sudo python2.7 setup.py install
    - "edd -h"

